### ISSUE TITLE
Ignore commands containing only '?'

### ISSUE THREAD

**Issue by spixy** [discord-csharp/modix-translator#9]
*Somebody:* `??`
*Modix:* `Error: UnknownCommand, Unknown command.`

### Proposition:
Ignore commands containing only `?` characters, aka `^[?]+` (regex).

(Moved from https://github.com/discord-csharp/MODiX/issues/806)

**Comment by Gnbrkm41** [comment]
Should be handled by https://github.com/discord-csharp/modix-translator/pull/6, I believe the change isn't just applied to the bot yet.

**Comment by spixy** [comment]
and its already applied 👍
